import pytest

from citeproof.role_lens import inspect_role_conflicts


@pytest.mark.parametrize(
    ("claim", "evidence"),
    [
        (
            "The model was trained on patient records.",
            "The model was evaluated on patient records.",
        ),
        (
            "GPT-4 generated the dataset annotations.",
            "Human annotators generated the dataset annotations, "
            "and GPT-4 was used to audit annotation quality.",
        ),
        (
            "The benchmark filters toxic prompts before evaluation.",
            "The benchmark evaluates models on toxic prompts and filters outputs after evaluation.",
        ),
        (
            "The dataset is released under a permissive MIT license.",
            "The code is released under an MIT license, "
            "but the dataset is available under a non-commercial license.",
        ),
        (
            "The model learns from gold human labels.",
            "The model learns from pseudo-labels generated by a teacher "
            "and is evaluated against gold human labels.",
        ),
        (
            "The QA system retrieves passages from Wikipedia.",
            "The QA system answers Wikipedia questions using passages retrieved from Common Crawl.",
        ),
    ],
)
def test_detects_role_provenance_conflicts(claim: str, evidence: str) -> None:
    findings = inspect_role_conflicts(claim, evidence)

    assert any("Role conflict" in finding for finding in findings)


@pytest.mark.parametrize(
    ("claim", "evidence"),
    [
        ("GPT-4 audited annotation quality.", "GPT-4 was used to audit annotation quality."),
        (
            "The dataset is released under a non-commercial license.",
            "The code is MIT licensed, but the dataset is available under a non-commercial license.",
        ),
        ("The model was evaluated on GLUE.", "The model was evaluated on GLUE."),
    ],
)
def test_ignores_matching_role_bindings(claim: str, evidence: str) -> None:
    assert inspect_role_conflicts(claim, evidence) == ()
