import pytest

from citeproof.adjudicator import adjudicate_evidence
from citeproof.models import FailureMode, Label


@pytest.mark.parametrize(
    ("claim", "evidence"),
    [
        (
            "The method improves calibration.",
            "Future work will test whether the method improves calibration.",
        ),
        ("Dropout improves robustness.", "We hypothesize that dropout improves robustness."),
        (
            "The method reduces hallucinations.",
            "The method is designed to reduce hallucinations.",
        ),
    ],
)
def test_assertion_status_tensions_block_full_support(claim: str, evidence: str) -> None:
    judgment = adjudicate_evidence(claim, evidence)

    assert judgment.label == Label.PARTIALLY_SUPPORTED
    assert judgment.failure_mode == FailureMode.SCOPE_OVERSTATEMENT


@pytest.mark.parametrize(
    ("claim", "evidence"),
    [
        (
            "The model was trained on patient records.",
            "The model was evaluated on patient records.",
        ),
        (
            "GPT-4 generated the dataset annotations.",
            "Human annotators generated the dataset annotations, "
            "and GPT-4 was used to audit annotation quality.",
        ),
        (
            "The benchmark filters toxic prompts before evaluation.",
            "The benchmark evaluates models on toxic prompts and filters outputs after evaluation.",
        ),
        (
            "The dataset is released under a permissive MIT license.",
            "The code is released under an MIT license, "
            "but the dataset is available under a non-commercial license.",
        ),
        (
            "The model learns from gold human labels.",
            "The model learns from pseudo-labels generated by a teacher "
            "and is evaluated against gold human labels.",
        ),
        (
            "The QA system retrieves passages from Wikipedia.",
            "The QA system answers Wikipedia questions using passages retrieved from Common Crawl.",
        ),
    ],
)
def test_role_conflicts_block_support(claim: str, evidence: str) -> None:
    judgment = adjudicate_evidence(claim, evidence)

    assert judgment.label == Label.CONTRADICTED
    assert judgment.failure_mode == FailureMode.ENTITY_CONFLICT
